name: Build & push image

on:
  push:
    branches: [main]
    tags: ["v*"]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/reusable-build.yml

    with:
      push: true
      image-name: ghcr.io/${{ github.repository }}:latest
